index:
    pattern: /
    route: "{application:default_bundle}::{application:default_controller}"

admin:
    pattern: /{admin:path}/?<method>?/?<random>?
    route: "Admin::Panel::$method"
    backslash: true