framework:
    secret: jdaifdsa0fhau9403hfu90ahur90fje9ujf0ajeu9c0u9a0er0macu9r0mau903a4mu90mu90DJUW90JUD90
    timezone: Europe/Moscow
    environment: dev
    
application:
    default: Main
    autoload_solutions: [] # Main:Simple, Main:Users, Dummy:Other...
    template_engine: Twig # Native, Twig
    log_file_max_size_mb: 2

recaptcha:
    public_key: 6LeSIMgSAAAAAJTxRSy7xxnyHmjUWPODhTBFWepp
    private_key: 6LeSIMgSAAAAADs7b2hVOeQPTceB5I1DaTuU1HaP

swift_transport:
    host: smtp.yandex.ru:25
    username: php.batman@yandex.ru
    password: batman.php

swift_vcard:
    email: php.batman@yandex.ru
    first_name: Batman
    last_name: Php
    
database:
    host: localhost
    driver: pdo_mysql
    charset: UTF8
