framework:
    secret: jdaifdsa0fhau9403hfu90ahur90fje9ujf0ajeu9c0u9a0er0macu9r0mau903a4mu90mu90DJUW90JUD90
    timezone: Europe/Moscow
    environment: dev
    
application:
    default: Main
    autoload_solutions: [] # Main:Simple, Main:Users, Dummy:Other...
    template_engine: Twig # Native, Twig
    log_file_max_size_mb: 2

recaptcha:
    public_key: 6LeSIMgSAAAAAJTxRSy7xxnyHmjUWPODhTBFWepp
    private_key: 6LeSIMgSAAAAADs7b2hVOeQPTceB5I1DaTuU1HaP

swiftmailer:
    smtp: smtp.yandex.ru
    email: php.batman@yandex.ru
    password: batman.php
    
database:
    host: localhost
    port: 3306
    charset: UTF8
