index:
    pattern: /
    route: Main::Main

admin:
    pattern: /admin
    route: Admin::Panel
    backslash: true

hello:
    pattern: /hello/<name>
    route: Main::Hello::index::$1
    backslash: true

users:
    pattern: /users/?<action>?/?<option>?
    route: Main::Users::$1::$2
    backslash: true
