index:
    pattern: /
    route: "{application:default_bundle}::{application:default_controller}"

admin:
    pattern: /{admin:path}/?<method>?/?<random>?
    route: "Admin::Panel::$method"
    backslash: true

hello:
    pattern: /hello/<name>
    route: "Main::Hello::index::$name"
    backslash: true

users:
    pattern: /users/?<action>?/?<option>?
    route: "Main::Users::$action::$option"
    backslash: true
