index_rule:
    pattern: /
    route: Main::Main::index

index_alternate:
    pattern: /demo
    route: Main::Main::index

hello:
    pattern: /hello/([a-zA-Z]+)(?:/)?
    route: Main::Hello::index::$1