index_rule:
    pattern: /
    route: Main::Main::index

index_alternate:
    pattern: /demo
    route: Main::Main::index

hello:
    pattern: /hello/<name>
    route: Main::Hello::index::$1
    backslash: true

users:
    pattern: /users/?<action>?/?<option>?
    route: Main::Users::$1::$2
    backslash: true
